"""Mechanical hygiene checks on the branch you are about to push.

    python diff_check.py owner/repo [--base REF] [--plan a.py,b.py] [--allow-generated]

Run inside the clone, on the feature branch. FAIL lines block the push; WARN
lines need a written reason in the PR notes or a fix.

Checks:
  - files outside the plan (when --plan is given)
  - lock files and generated files (DO NOT EDIT / @generated markers)
  - likely secrets in added lines
  - non-ASCII characters in added lines where the profile requires ASCII (ascii_only: yes or globs)
  - commits missing Signed-off-by when the profile says dco: yes
  - commit signatures when the profile says signed_commits: yes
  - AI disclosure trailers: required when the profile puts disclosure in commit trailers,
    flagged otherwise
  - whitespace errors (git diff --check)
  - size above the 90th percentile of recently merged outside PRs (profile)
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass

from _config import glob_match, load_profile, scope_globs, truthy
from _gh import default_base, run_git_or_exit, use_utf8_stdout

LOCK_FILES = (
    "**/package-lock.json",
    "**/yarn.lock",
    "**/pnpm-lock.yaml",
    "**/poetry.lock",
    "**/uv.lock",
    "**/Pipfile.lock",
    "**/Cargo.lock",
    "**/composer.lock",
    "**/Gemfile.lock",
    "**/go.sum",
)
GENERATED_MARKER = re.compile(r"Code generated .* DO NOT EDIT|@generated|<auto-generated")
SECRET_PATTERNS = {
    "AWS access key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "GitHub token": re.compile(r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{30,}\b|\bgithub_pat_[A-Za-z0-9_]{40,}\b"),
    "Slack token": re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}\b"),
    "Google API key": re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b"),
    "OpenAI/Anthropic-style key": re.compile(r"\bsk-(?:ant-)?[A-Za-z0-9_-]{20,}\b"),
    "private key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----"),
}
AI_TRAILER = re.compile(
    r"(?im)^(?:co-authored-by|generated-by|assisted-by):.*\b(?:claude|copilot|gpt|codex|cursor|ai)\b"
)


@dataclass(frozen=True)
class Finding:
    level: str  # FAIL or WARN
    message: str


def added_lines(diff: str) -> dict[str, list[tuple[int, str]]]:
    """path -> [(new line number, text)] for every added line of a unified diff (from `git diff -U0`)."""
    result: dict[str, list[tuple[int, str]]] = {}
    path, line_no = None, 0
    for raw in diff.splitlines():
        if raw.startswith("+++ "):
            target = raw[4:]
            path = None if target == "/dev/null" else target[2:] if target.startswith("b/") else target
            continue
        hunk = re.match(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@", raw)
        if hunk:
            line_no = int(hunk.group(1))
            continue
        if path is None:
            continue
        if raw.startswith("+") and not raw.startswith("+++"):
            result.setdefault(path, []).append((line_no, raw[1:]))
            line_no += 1
        elif not raw.startswith("-"):
            line_no += 1
    return result


def check_files(files: list[str], plan: list[str] | None, allow_generated: bool) -> list[Finding]:
    findings = []
    if plan is not None:
        for f in files:
            if not any(f == p or glob_match(p, f) for p in plan):
                findings.append(Finding("FAIL", f"{f}: not in the plan; drop it or add it to the plan on purpose"))
    for f in files:
        if any(glob_match(pattern, f) for pattern in LOCK_FILES) and not allow_generated:
            findings.append(Finding("WARN", f"{f}: lock file changed; keep only if the dependency change is the point"))
    return findings


def check_added(
    added: dict[str, list[tuple[int, str]]], ascii_globs: list[str] | bool, allow_generated: bool
) -> list[Finding]:
    """ascii_globs: paths where only ASCII is allowed (True means everywhere, False nowhere)."""
    if isinstance(ascii_globs, bool):
        ascii_globs = ["**"] if ascii_globs else []
    findings = []
    for path, lines in added.items():
        ascii_only = any(glob_match(g, path) for g in ascii_globs)
        for number, text in lines:
            for name, pattern in SECRET_PATTERNS.items():
                if pattern.search(text):
                    findings.append(Finding("FAIL", f"{path}:{number}: looks like a {name}"))
            if GENERATED_MARKER.search(text) and not allow_generated:
                findings.append(Finding("WARN", f"{path}:{number}: generated-file marker; regenerate, don't hand-edit"))
            if ascii_only and any(ord(ch) > 127 for ch in text):
                bad = "".join(sorted({ch for ch in text if ord(ch) > 127}))
                findings.append(Finding("FAIL", f"{path}:{number}: non-ASCII {bad!r} in a repo that requires ASCII"))
    return findings


def check_commits(messages: list[str], dco: bool, trailer_regex: str | None = None) -> list[Finding]:
    """DCO sign-off on every commit; AI trailers only where the repo asks for them (trailer_regex)."""
    findings = []
    for message in messages:
        subject = message.strip().splitlines()[0] if message.strip() else "(empty)"
        if dco and "Signed-off-by:" not in message:
            findings.append(Finding("FAIL", f"commit '{subject[:60]}' has no Signed-off-by (repo requires DCO)"))
        if AI_TRAILER.search(message) and not trailer_regex:
            findings.append(
                Finding("WARN", f"commit '{subject[:60]}' has an AI attribution trailer the profile does not ask for")
            )
    if trailer_regex and messages and not any(re.search(trailer_regex, m) for m in messages):
        findings.append(
            Finding(
                "FAIL",
                f"the repo wants AI disclosure in a commit trailer (regex {trailer_regex}) and no commit has it; "
                "if the user's own rules forbid AI trailers, stop and let the user decide",
            )
        )
    return findings


def check_signatures(statuses: list[tuple[str, str]], required: bool) -> list[Finding]:
    """statuses: (subject, %G? code). G/U/X/Y/R are signed; N is unsigned; B is a bad signature; E unverifiable."""
    if not required:
        return []
    findings = []
    for subject, code in statuses:
        if code in {"N", "B"}:
            what = "unsigned" if code == "N" else "has a bad signature"
            findings.append(Finding("FAIL", f"commit '{subject[:60]}' is {what}; the repo requires signed commits"))
        elif code == "E":
            findings.append(Finding("WARN", f"commit '{subject[:60]}' signature cannot be checked locally"))
    return findings


def disclosure_trailer_regex(facts: dict[str, str]) -> str | None:
    """The profile's disclosure regex when disclosure belongs in commit trailers, else None."""
    location = facts.get("disclosure_location", "")
    pattern = facts.get("disclosure_regex", "")
    if "commit-trailer" not in location or not pattern or "fill in" in pattern.lower():
        return None
    return pattern


def check_size(files: int, lines: int, facts: dict[str, str]) -> list[Finding]:
    findings = []
    for value, key, label in ((files, "merged_pr_files_p90", "files"), (lines, "merged_pr_lines_p90", "lines")):
        limit = facts.get(key, "").split(" ")[0]
        if limit.isdigit() and int(limit) and value > int(limit):
            findings.append(
                Finding("WARN", f"{value} {label} changed; 90% of recent merged outside PRs change {limit} or fewer")
            )
    return findings


def whitespace_errors(base: str) -> str:
    """`git diff --check` exits non-zero when it finds problems, so it cannot go through git()."""
    result = subprocess.run(
        ["git", "diff", "--check", f"{base}...HEAD"], capture_output=True, text=True, encoding="utf-8", errors="replace"
    )
    return result.stdout


def main() -> None:
    use_utf8_stdout()
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("repo", help="owner/repo (selects the profile)")
    parser.add_argument("--base", help="base ref (default: detected upstream default branch)")
    parser.add_argument("--plan", help="comma-separated files or globs you intended to change")
    parser.add_argument("--allow-generated", action="store_true", help="the change is meant to touch generated files")
    args = parser.parse_args()
    base = args.base or default_base()

    facts, _rules, profile = load_profile(args.repo)
    if profile is None:
        print(f"WARN: no profile for {args.repo}; DCO, ASCII, signing and size checks use defaults")
    files = [f for f in run_git_or_exit(["diff", "--name-only", f"{base}...HEAD"]).splitlines() if f.strip()]
    diff = run_git_or_exit(["diff", "-U0", f"{base}...HEAD"])
    added = added_lines(diff)
    numstat = run_git_or_exit(["diff", "--numstat", f"{base}...HEAD"]).splitlines()
    total_lines = sum(
        int(a) + int(d) for a, d, *_ in (row.split("\t") for row in numstat) if a.isdigit() and d.isdigit()
    )
    messages = [m for m in run_git_or_exit(["log", "--format=%B%x00", f"{base}..HEAD"]).split("\x00") if m.strip()]
    statuses = [
        tuple(row.split("\x00", 1)[::-1])
        for row in run_git_or_exit(["log", "--format=%G?%x00%s", f"{base}..HEAD"]).splitlines()
        if "\x00" in row
    ]

    plan = [p.strip() for p in args.plan.split(",") if p.strip()] if args.plan else None
    findings = check_files(files, plan, args.allow_generated)
    findings += check_added(added, scope_globs(facts.get("ascii_only")), args.allow_generated)
    findings += check_commits(messages, truthy(facts.get("dco")), disclosure_trailer_regex(facts))
    findings += check_signatures(statuses, truthy(facts.get("signed_commits")))
    findings += check_size(len(files), total_lines, facts)
    whitespace = whitespace_errors(base) if files else ""
    if whitespace.strip():
        findings.append(Finding("WARN", "whitespace errors:\n" + whitespace.strip()[:600]))

    print(f"{len(files)} files, {total_lines} lines changed, {len(messages)} commits against {base}")
    for finding in findings:
        print(f"{finding.level}: {finding.message}")
    failed = any(f.level == "FAIL" for f in findings)
    print("RESULT: " + ("FAIL" if failed else "PASS (read every WARN)" if findings else "PASS"))
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
